server:
  servlet:
    context-path: /flysix

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  sql:
    init:
      mode: always

  main:
    allow-circular-references: true

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    username:
    host: smtp.gmail.com
    protocol: smtp
    password:
    port: 587

stripe:
  apiKey:
  endpoint-secret: