server:
  servlet:
    context-path: /flysix

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/flysixDB?createDatabaseIfNotExist=true
    password: 9696
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  sql:
    init:
      mode: always

  main:
    allow-circular-references: true

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    username: everythingneox16@gmail.com
    host: smtp.gmail.com
    protocol: smtp
    password:
    port: 587

stripe:
  apiKey: sk_test_XXiQh8dGMkNRYTqrC6p2tXx0002jYnF074
  endpoint-secret: whsec_ca8525e0e69037e7864397175bfeae12b8ea51755f8b01bcac0916ddf089832c